services:
  nearby:
    image: node:20-alpine
    container_name: nearby-dev
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "5050:5001"
    env_file:
      - .env.development
    environment:
      NODE_ENV: development
    depends_on:
      - mongo
    networks:
      - nearby-net

  mongo:
    image: mongo:6.0
    container_name: nearby-mongo-dev
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: nearby

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    networks:
      - nearby-net

networks:
  nearby-net:
    name: nearby-net

volumes:
  mongo-data: